SELECT: "SELECT\t*\nFROM\t"
#SELECT_WHERE: "SELECT\t*\nFROM\t\nWHERE\t"
#SELECT_WHERE_GROUP_ORDER: "SELECT\t*\nFROM\t\nWHERE\t\nGROUP\tBY\t\nORDER\tBY\t"
UPDATE: "UPDATE\t"
INSERT: "INSERT\tINTO\t"
CREATE_TABLE: "CREATE\tTABLE\t"
CREATE_VIEW: "CREATE\tVIEW\t"
ORDER: "ORDER\tBY\t"
GROUP: "GROUP\tBY\t"
HAVING: "HAVING\t"
WHERE: "WHERE\t"
PARTITION: "PARTITION\tBY\t"
TRUNCATE_TABLE: "TRUNCATE\tTABLE\t"
DROP_TABLE: "DROP\tTABLE\t"
DROP_VIEW: "DROP\tVIEW\t"
DISTRIBUTE: "DISTRIBUTE\tON\tRANDOM;"
GENERATE: "GENERATE\tSTATISTICS\tON\t"
MAX: "MAX(column) -> int"
MIN: "MIN(column) -> int"
COUNT: "COUNT(*) -> int"
